permalink: /:categories:month/:title
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
url: http://erkankoca.github.com
exclude:
        - Rakefile
        - Makefile
        - presentation.md
        - presentation.html
        - presentation.png
        - media

account: erknkoca
archive: Depo
assets: /assets
author: Erkan Koca
disqus: erknkoca
email: erkan.koca@bil.omu.edu.tr
googleanalyticsid: 
facebook: https://facebook.com/erknkca
logo: /assets/19/19-normal-128x128.png
organization: 19
related: Diğer Girdiler
repository: erkankoca.github.com
ribbon: GitHub
title: Erkan Koca
twitter: 

navigator:
        0: Teknik Olmayan Yazılar
        1: Teknik Yazılar
        9: Kısa Notlar
